victoire_core:
    widgets:
        Redactor:
            class: Victoire\Widget\RedactorBundle\Entity\WidgetRedactor
            name: Redactor
            parent: Text

jms_translation:
   configs:
        victoire_redactor_bundle:
            dirs: ['@VictoireWidgetRedactorBundle']
            output_dir: '@VictoireWidgetRedactorBundle/Resources/translations'
