victoire_core:
    widgets:
        redactor:
            class: "Victoire\Widget\RedactorBundle\Entity\WidgetRedactor"
            name: redactor

jms_translation:
   configs:
        victoire_redactor_bundle:
            dirs: ["@VictoireRedactorBundle"]
            output_dir: "@VictoireRedactorBundle/Resources/translations"
